### ISSUE TITLE
cant display more than one magazine

### ISSUE THREAD

**Issue by jagfly** [BesrourMS/magazine#5]
HI
i installed the magazine theme for pico and followed the directions but the page is only showing one magazine, not the 16 specified in the config file. i have tried doing the install a couple of times and verified ive done everything, but i only see one magazine. 

i wanted to customize the site to use just a few (say 6 "magazine" links) but no matter what number magazines i put in the config file i only see one (the first sample, "we eat alot"). can you tell me what i may have wrong or if there is anything wrong with the install documentation?

thanks
matt

**Comment by elkwaet** [comment]
Hi @jagfly ,
Am starting with Pico and specialy this theme "Magazine" also; and can say i got many problem too.
I got the same issue with number of posts display according number set in configuration files. So, solution i find after many essay is to set the number to 4:
`$config['numPerPage'] = 4; // Nombre d'articles à afficher par page`
Since the pagination works and don't load realy to switch, it solved [for my case](https://blog.elkwaet.tk) .
